# fly.toml — FedEx Transit (WordPress)
# https://fly.io/docs/reference/configuration/

app = 'borinho102-fedex-transit'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  WORDPRESS_DB_NAME = 'billing_ftdb'
  WORDPRESS_DB_USER = 'billing_ft_root'
  WORDPRESS_DB_HOST = '193.203.169.34'
  WORDPRESS_TABLE_PREFIX = 'fedex_'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '90s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
